name: Email Step Workflow

on:
  workflow_dispatch:   # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f3000075@ds.study.iitm.ac.in
        run: echo "Hello, world!"
